---
apiVersion: "batch/v1"
kind: "Job"
metadata:
  annotations:
    annotation1: "some-very-long-annotation"
  labels:
    label1: "maximum-length-of-63-characters"
  name: "pi"
spec:
  template:
    spec:
      containers:
      - args:
        - "perl"
        - "-Mbignum=bpi"
        - "-wle"
        - "print bpi(2000)"
        image: "perl"
        name: "pi"
      restartPolicy: "Never"
